In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.11.0


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 3s 0us/step


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

2023-01-06 16:54:40.489980: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-06 16:54:40.494919: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-01-06 16:54:40.495678: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Metal device set to: Apple M1


In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.25280297, -0.15502842,  0.3619733 ,  0.3311    , -0.35151467,
         0.20096546,  0.01039848,  0.62351704, -0.45444888,  0.10354935]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.11178589, 0.07434779, 0.12468065, 0.12089016, 0.06108508,
        0.10613881, 0.08772271, 0.16195191, 0.05511012, 0.09628684]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.2430072

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


2023-01-06 16:56:00.059570: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-01-06 16:56:01.307031: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x7f9e7737e5a0
2023-01-06 16:56:01.307088: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x7f9e7737e5a0
2023-01-06 16:56:01.450782: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x7f9e7737e5a0
2023-01-06 16:56:01.450831: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x7f9e7737e5a0


NotFoundError: Graph execution error:

Detected at node 'StatefulPartitionedCall_2' defined at (most recent call last):
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/traitlets/config/application.py", line 1041, in launch_instance
      app.start()
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 711, in start
      self.io_loop.start()
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
      self._run_once()
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/asyncio/base_events.py", line 1899, in _run_once
      handle._run()
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/asyncio/events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
      await self.process_one()
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 499, in process_one
      await dispatch(*args)
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
      await result
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 729, in execute_request
      reply_content = await reply_content
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 411, in do_execute
      res = shell.run_cell(
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 530, in run_cell
      return super().run_cell(*args, **kwargs)
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2945, in run_cell
      result = self._run_cell(
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3000, in _run_cell
      return runner(coro)
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3203, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3382, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3442, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "/var/folders/g3/q02s8jx14gg19r3n__xvvf380000gn/T/ipykernel_46974/2168363081.py", line 1, in <module>
      model.fit(x_train, y_train, epochs=5)
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/keras/engine/training.py", line 1650, in fit
      tmp_logs = self.train_function(iterator)
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/keras/engine/training.py", line 1249, in train_function
      return step_function(self, iterator)
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/keras/engine/training.py", line 1233, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/keras/engine/training.py", line 1222, in run_step
      outputs = model.train_step(data)
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/keras/engine/training.py", line 1027, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 527, in minimize
      self.apply_gradients(grads_and_vars)
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1140, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 634, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1166, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1216, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "/Users/nilabhshivam/opt/anaconda3/envs/env_tensorflow/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1211, in apply_grad_to_update_var
      return self._update_step_xla(grad, var, id(self._var_key(var)))
Node: 'StatefulPartitionedCall_2'
could not find registered platform with id: 0x7f9e7737e5a0
	 [[{{node StatefulPartitionedCall_2}}]] [Op:__inference_train_function_798]

In [11]:
model.evaluate(x_test,  y_test, verbose=2)

2023-01-06 16:56:17.178907: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


313/313 - 2s - loss: 2.3645 - accuracy: 0.1234 - 2s/epoch - 5ms/step


[2.364466667175293, 0.1234000027179718]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.0975536 , 0.08022226, 0.140087  , 0.11354554, 0.11104622,
        0.09280606, 0.08811946, 0.11910985, 0.06350755, 0.09400253],
       [0.0400231 , 0.04845378, 0.23756526, 0.2310508 , 0.04845706,
        0.0820749 , 0.02623279, 0.11426137, 0.09271277, 0.07916825],
       [0.10612857, 0.09324371, 0.13084318, 0.12935828, 0.08890481,
        0.10898501, 0.07848912, 0.10572944, 0.09666888, 0.06164902],
       [0.06091945, 0.03836514, 0.26629826, 0.08219348, 0.1117138 ,
        0.06095633, 0.04961192, 0.07559411, 0.06796116, 0.1863864 ],
       [0.08964211, 0.07121184, 0.14479037, 0.09263627, 0.11449633,
        0.05554465, 0.04429356, 0.18167111, 0.06840546, 0.13730834]],
      dtype=float32)>